import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import Footer from '@/components/element/Footer';

export const metadata: Metadata = {
  title: 'จัดการลูกค้า | Agent Dashboard | 1StopInsurance',
  description: 'หน้าจัดการข้อมูลลูกค้าสำหรับตัวแทนประกัน',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      <body className="font-sans text-gray-800 flex flex-col min-h-screen bg-[#f0f6ff]">
        {children}
        <Footer />
      </body>
    </html>
  );
}
